# Generated by Django 4.0.5 on 2022-07-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimaryImg', models.ImageField(default='flower-bouquet.jpeg', upload_to='')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_4', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
