# Generated by Django 4.0.5 on 2022-07-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='PrimaryImg',
            new_name='primaryImg',
        ),
    ]
