# Generated by Django 4.0.5 on 2022-06-30 13:21

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='primaryImg',
            field=models.ImageField(upload_to=product.models.upload_to),
        ),
    ]
