# Generated by Django 4.0.5 on 2022-06-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.URLField(blank=True, max_length=500, null=True)),
                ('intagram', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter', models.URLField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
