# Generated by Django 4.0.5 on 2022-07-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_social_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='intagram',
            new_name='instagram',
        ),
    ]
